// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: entpb/ext.proto

package entpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_entpb_ext_proto protoreflect.FileDescriptor

const file_entpb_ext_proto_rawDesc = "" +
	"\n" +
	"\x0fentpb/ext.proto\x12\x05entpb\x1a\x11entpb/entpb.proto\x1a\x1bgoogle/protobuf/empty.proto2K\n" +
	"\vNoopService\x12<\n" +
	"\bCrickets\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B9Z7entgo.io/contrib/entproto/internal/todo/ent/proto/entpbb\x06proto3"

var file_entpb_ext_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_entpb_ext_proto_depIdxs = []int32{
	0, // 0: entpb.NoopService.Crickets:input_type -> google.protobuf.Empty
	0, // 1: entpb.NoopService.Crickets:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entpb_ext_proto_init() }
func file_entpb_ext_proto_init() {
	if File_entpb_ext_proto != nil {
		return
	}
	file_entpb_entpb_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entpb_ext_proto_rawDesc), len(file_entpb_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entpb_ext_proto_goTypes,
		DependencyIndexes: file_entpb_ext_proto_depIdxs,
	}.Build()
	File_entpb_ext_proto = out.File
	file_entpb_ext_proto_goTypes = nil
	file_entpb_ext_proto_depIdxs = nil
}
