// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: opts.proto

package ent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Schema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gen           *bool                  `protobuf:"varint,1,opt,name=gen" json:"gen,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_opts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_opts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_opts_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetGen() bool {
	if x != nil && x.Gen != nil {
		return *x.Gen
	}
	return false
}

func (x *Schema) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Optional      *bool                  `protobuf:"varint,1,opt,name=optional" json:"optional,omitempty"`
	Nillable      *bool                  `protobuf:"varint,2,opt,name=nillable" json:"nillable,omitempty"`
	Unique        *bool                  `protobuf:"varint,3,opt,name=unique" json:"unique,omitempty"`
	Sensitive     *bool                  `protobuf:"varint,4,opt,name=sensitive" json:"sensitive,omitempty"`
	Immutable     *bool                  `protobuf:"varint,5,opt,name=immutable" json:"immutable,omitempty"`
	Comment       *string                `protobuf:"bytes,6,opt,name=comment" json:"comment,omitempty"`
	StructTag     *string                `protobuf:"bytes,7,opt,name=struct_tag,json=structTag" json:"struct_tag,omitempty"`
	StorageKey    *string                `protobuf:"bytes,8,opt,name=storage_key,json=storageKey" json:"storage_key,omitempty"`
	SchemaType    map[string]string      `protobuf:"bytes,9,rep,name=schema_type,json=schemaType" json:"schema_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_opts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_opts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_opts_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetOptional() bool {
	if x != nil && x.Optional != nil {
		return *x.Optional
	}
	return false
}

func (x *Field) GetNillable() bool {
	if x != nil && x.Nillable != nil {
		return *x.Nillable
	}
	return false
}

func (x *Field) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

func (x *Field) GetSensitive() bool {
	if x != nil && x.Sensitive != nil {
		return *x.Sensitive
	}
	return false
}

func (x *Field) GetImmutable() bool {
	if x != nil && x.Immutable != nil {
		return *x.Immutable
	}
	return false
}

func (x *Field) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *Field) GetStructTag() string {
	if x != nil && x.StructTag != nil {
		return *x.StructTag
	}
	return ""
}

func (x *Field) GetStorageKey() string {
	if x != nil && x.StorageKey != nil {
		return *x.StorageKey
	}
	return ""
}

func (x *Field) GetSchemaType() map[string]string {
	if x != nil {
		return x.SchemaType
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unique        *bool                  `protobuf:"varint,1,opt,name=unique" json:"unique,omitempty"`
	Ref           *string                `protobuf:"bytes,2,opt,name=ref" json:"ref,omitempty"`
	Required      *bool                  `protobuf:"varint,3,opt,name=required" json:"required,omitempty"`
	Field         *string                `protobuf:"bytes,4,opt,name=field" json:"field,omitempty"`
	StorageKey    *Edge_StorageKey       `protobuf:"bytes,5,opt,name=storage_key,json=storageKey" json:"storage_key,omitempty"`
	StructTag     *string                `protobuf:"bytes,6,opt,name=struct_tag,json=structTag" json:"struct_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_opts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_opts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_opts_proto_rawDescGZIP(), []int{2}
}

func (x *Edge) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

func (x *Edge) GetRef() string {
	if x != nil && x.Ref != nil {
		return *x.Ref
	}
	return ""
}

func (x *Edge) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *Edge) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

func (x *Edge) GetStorageKey() *Edge_StorageKey {
	if x != nil {
		return x.StorageKey
	}
	return nil
}

func (x *Edge) GetStructTag() string {
	if x != nil && x.StructTag != nil {
		return *x.StructTag
	}
	return ""
}

type Edge_StorageKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *string                `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge_StorageKey) Reset() {
	*x = Edge_StorageKey{}
	mi := &file_opts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge_StorageKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge_StorageKey) ProtoMessage() {}

func (x *Edge_StorageKey) ProtoReflect() protoreflect.Message {
	mi := &file_opts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge_StorageKey.ProtoReflect.Descriptor instead.
func (*Edge_StorageKey) Descriptor() ([]byte, []int) {
	return file_opts_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Edge_StorageKey) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

func (x *Edge_StorageKey) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

var file_opts_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Schema)(nil),
		Field:         150119,
		Name:          "ent.schema",
		Tag:           "bytes,150119,opt,name=schema",
		Filename:      "opts.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Field)(nil),
		Field:         150119,
		Name:          "ent.field",
		Tag:           "bytes,150119,opt,name=field",
		Filename:      "opts.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Edge)(nil),
		Field:         150120,
		Name:          "ent.edge",
		Tag:           "bytes,150120,opt,name=edge",
		Filename:      "opts.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional ent.Schema schema = 150119;
	E_Schema = &file_opts_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional ent.Field field = 150119;
	E_Field = &file_opts_proto_extTypes[1]
	// optional ent.Edge edge = 150120;
	E_Edge = &file_opts_proto_extTypes[2]
)

var File_opts_proto protoreflect.FileDescriptor

const file_opts_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"opts.proto\x12\x03ent\x1a google/protobuf/descriptor.proto\".\n" +
	"\x06Schema\x12\x10\n" +
	"\x03gen\x18\x01 \x01(\bR\x03gen\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe9\x02\n" +
	"\x05Field\x12\x1a\n" +
	"\boptional\x18\x01 \x01(\bR\boptional\x12\x1a\n" +
	"\bnillable\x18\x02 \x01(\bR\bnillable\x12\x16\n" +
	"\x06unique\x18\x03 \x01(\bR\x06unique\x12\x1c\n" +
	"\tsensitive\x18\x04 \x01(\bR\tsensitive\x12\x1c\n" +
	"\timmutable\x18\x05 \x01(\bR\timmutable\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x1d\n" +
	"\n" +
	"struct_tag\x18\a \x01(\tR\tstructTag\x12\x1f\n" +
	"\vstorage_key\x18\b \x01(\tR\n" +
	"storageKey\x12;\n" +
	"\vschema_type\x18\t \x03(\v2\x1a.ent.Field.SchemaTypeEntryR\n" +
	"schemaType\x1a=\n" +
	"\x0fSchemaTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x01\n" +
	"\x04Edge\x12\x16\n" +
	"\x06unique\x18\x01 \x01(\bR\x06unique\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x14\n" +
	"\x05field\x18\x04 \x01(\tR\x05field\x125\n" +
	"\vstorage_key\x18\x05 \x01(\v2\x14.ent.Edge.StorageKeyR\n" +
	"storageKey\x12\x1d\n" +
	"\n" +
	"struct_tag\x18\x06 \x01(\tR\tstructTag\x1a<\n" +
	"\n" +
	"StorageKey\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns:F\n" +
	"\x06schema\x12\x1f.google.protobuf.MessageOptions\x18\xe7\x94\t \x01(\v2\v.ent.SchemaR\x06schema:A\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xe7\x94\t \x01(\v2\n" +
	".ent.FieldR\x05field:>\n" +
	"\x04edge\x12\x1d.google.protobuf.FieldOptions\x18\xe8\x94\t \x01(\v2\t.ent.EdgeR\x04edgeB:Z8entgo.io/contrib/entproto/cmd/protoc-gen-ent/options/ent"

var (
	file_opts_proto_rawDescOnce sync.Once
	file_opts_proto_rawDescData []byte
)

func file_opts_proto_rawDescGZIP() []byte {
	file_opts_proto_rawDescOnce.Do(func() {
		file_opts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opts_proto_rawDesc), len(file_opts_proto_rawDesc)))
	})
	return file_opts_proto_rawDescData
}

var file_opts_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_opts_proto_goTypes = []any{
	(*Schema)(nil),                      // 0: ent.Schema
	(*Field)(nil),                       // 1: ent.Field
	(*Edge)(nil),                        // 2: ent.Edge
	nil,                                 // 3: ent.Field.SchemaTypeEntry
	(*Edge_StorageKey)(nil),             // 4: ent.Edge.StorageKey
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 6: google.protobuf.FieldOptions
}
var file_opts_proto_depIdxs = []int32{
	3, // 0: ent.Field.schema_type:type_name -> ent.Field.SchemaTypeEntry
	4, // 1: ent.Edge.storage_key:type_name -> ent.Edge.StorageKey
	5, // 2: ent.schema:extendee -> google.protobuf.MessageOptions
	6, // 3: ent.field:extendee -> google.protobuf.FieldOptions
	6, // 4: ent.edge:extendee -> google.protobuf.FieldOptions
	0, // 5: ent.schema:type_name -> ent.Schema
	1, // 6: ent.field:type_name -> ent.Field
	2, // 7: ent.edge:type_name -> ent.Edge
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	5, // [5:8] is the sub-list for extension type_name
	2, // [2:5] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_opts_proto_init() }
func file_opts_proto_init() {
	if File_opts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opts_proto_rawDesc), len(file_opts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_opts_proto_goTypes,
		DependencyIndexes: file_opts_proto_depIdxs,
		MessageInfos:      file_opts_proto_msgTypes,
		ExtensionInfos:    file_opts_proto_extTypes,
	}.Build()
	File_opts_proto = out.File
	file_opts_proto_goTypes = nil
	file_opts_proto_depIdxs = nil
}
